"""World thumbnail path

Revision ID: 34f2d3b8dc01
Revises: b7a7bced3469
Create Date: 2026-02-04 12:11:04.973084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34f2d3b8dc01'
down_revision = 'b7a7bced3469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_path', sa.String(length=255), nullable=False))
        batch_op.drop_column('body')

    with op.batch_alter_table('world', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_path', sa.String(length=255), nullable=False))
        batch_op.drop_index(batch_op.f('ix_world_icon_path'))
        batch_op.drop_column('icon_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon_path', sa.VARCHAR(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_world_icon_path'), ['icon_path'], unique=False)
        batch_op.drop_column('thumbnail_path')

    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('body_path')

    # ### end Alembic commands ###
