"""add bio to World

Revision ID: ae35f0cbb9ca
Revises: 34f2d3b8dc01
Create Date: 2026-02-05 12:30:32.761582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae35f0cbb9ca'
down_revision = '34f2d3b8dc01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world', schema=None) as batch_op:
        batch_op.drop_column('info')

    # ### end Alembic commands ###
