"""add pins

Revision ID: b2dba2a3ec66
Revises: f2dc0b067c1e
Create Date: 2026-02-18 16:56:21.348263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2dba2a3ec66'
down_revision = 'f2dc0b067c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('x_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('y_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('target_map_id', sa.Integer(), nullable=True),
    sa.Column('added', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['map.id'], name='fk_pin_map', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_map_id'], ['map.id'], name='fk_pin_target_map', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pin_added'), ['added'], unique=False)
        batch_op.create_index(batch_op.f('ix_pin_map_id'), ['map_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pin_target_map_id'), ['target_map_id'], unique=False)

    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_map_world_id'))
        batch_op.drop_constraint(batch_op.f('fk_map_world'), type_='foreignkey')
        batch_op.drop_column('world_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('world_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_map_world'), 'world', ['world_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_map_world_id'), ['world_id'], unique=False)

    with op.batch_alter_table('pin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pin_target_map_id'))
        batch_op.drop_index(batch_op.f('ix_pin_map_id'))
        batch_op.drop_index(batch_op.f('ix_pin_added'))

    op.drop_table('pin')
    # ### end Alembic commands ###
