"""map table

Revision ID: b7a7bced3469
Revises: 89e06c5d44df
Create Date: 2026-02-04 10:57:23.224096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7a7bced3469'
down_revision = '89e06c5d44df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=255), nullable=False),
    sa.Column('added', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['world.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_map_added'), ['added'], unique=False)
        batch_op.create_index(batch_op.f('ix_map_world_id'), ['world_id'], unique=False)

    with op.batch_alter_table('world', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_world_created'), ['created'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_world_created'))
        batch_op.drop_column('created')

    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_map_world_id'))
        batch_op.drop_index(batch_op.f('ix_map_added'))

    op.drop_table('map')
    # ### end Alembic commands ###
