"""Update Map

Revision ID: d5fad9ea4b54
Revises: b2dba2a3ec66
Create Date: 2026-02-19 16:37:37.114935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5fad9ea4b54'
down_revision = 'b2dba2a3ec66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('world_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_map_world_id'), ['world_id'], unique=False)
        batch_op.create_foreign_key('fk_map_world', 'world', ['world_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.drop_constraint('fk_map_world', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_map_world_id'))
        batch_op.drop_column('world_id')

    # ### end Alembic commands ###
