"""Recreate migrations

Revision ID: f2dc0b067c1e
Revises: 
Create Date: 2026-02-10 16:37:39.391431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2dc0b067c1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('body_path', sa.String(length=255), nullable=False),
    sa.Column('added', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['world.id'], name='fk_map_world'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_map_added'), ['added'], unique=False)
        batch_op.create_index(batch_op.f('ix_map_world_id'), ['world_id'], unique=False)

    op.create_table('world',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=255), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('info', sa.String(length=140), nullable=True),
    sa.Column('primary_map_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['primary_map_id'], ['map.id'], name='fk_world_primary_map'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('world', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_world_created'), ['created'], unique=False)
        batch_op.create_index(batch_op.f('ix_world_name'), ['name'], unique=True)

    op.create_table('map_connections',
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('connected_map_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['connected_map_id'], ['map.id'], ),
    sa.ForeignKeyConstraint(['map_id'], ['map.id'], ),
    sa.PrimaryKeyConstraint('map_id', 'connected_map_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_connections')
    with op.batch_alter_table('world', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_world_name'))
        batch_op.drop_index(batch_op.f('ix_world_created'))

    op.drop_table('world')
    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_map_world_id'))
        batch_op.drop_index(batch_op.f('ix_map_added'))

    op.drop_table('map')
    # ### end Alembic commands ###
